### ISSUE TITLE
adjustment_height in deconv_2d does not apply into the subgraph

### ISSUE THREAD

**Issue by WenheLI** [google/XNNPACK#1555] opened 2021-06-19 13:33 UTC
Hi, I am trying to config the `adjustment_height` param in the `deconv_2d` node by setting value in `xnn_define_deconvolution_2d`.
However, it seems that param does not take effect. With further investigation, I found the code does not apply the `adjustment_height`.

https://github.com/google/XNNPACK/blob/a9992250ee0f58ee9b26f8e4b7c2c82f358d3b34/src/subgraph/deconvolution-2d.c#L233-L255

Just wondering if it is something intended and if so how should I config the `adjustment_height`.

**Comment by Maratyszcza** [comment] 2021-06-22 17:29
Thank you for reporting. Your #1556 is now merged, and I believe the issue is fixed.

**Closed by Maratyszcza** 2021-06-22 17:29 UTC
